import { db, Quiz, Question, QuizType, Student } from './mockDb';

// AI Quiz Agent system to simulate concept extraction and quiz generation
interface ConceptPool {
  subject: string;
  concepts: {
    name: string;
    questions: Omit<Question, 'id'>[];
  }[];
}

const AI_QUESTION_POOL: ConceptPool[] = [
  {
    subject: 'Physics',
    concepts: [
      {
        name: 'Electromagnetism & Induction',
        questions: [
          {
            type: 'MCQ',
            question: 'Which of the following represents Faraday\'s law of electromagnetic induction?',
            options: [
              'e = - dPhi / dt',
              'e = B * L * v',
              'F = q * (v x B)',
              'Ampere\'s Law'
            ],
            correctAnswer: '0',
            explanation: 'Faraday\'s law states that the induced electromotive force (emf) is equal to the negative rate of change of magnetic flux (dPhi/dt).'
          },
          {
            type: 'MCQ',
            question: 'Lenz\'s law is a consequence of the law of conservation of:',
            options: ['Charge', 'Momentum', 'Energy', 'Mass'],
            correctAnswer: '2',
            explanation: 'Lenz\'s law enforces conservation of energy: the electrical energy generated by induction comes from the mechanical work done in moving the magnet.'
          },
          {
            type: 'TRUE_FALSE',
            question: 'A magnetic field can accelerate a charged particle by changing its speed.',
            correctAnswer: 'false',
            explanation: 'A magnetic force is always perpendicular to velocity (F = qv x B), so it does zero work and can only change direction, not speed.'
          },
          {
            type: 'CASE_STUDY',
            question: 'In a fusion reactor, a heavy wire loop is placed near an alternating magnetic source. Describe why currents flow in the loop, referencing Faraday\'s & Lenz\'s laws.',
            correctAnswer: 'The alternating magnetic source creates a changing magnetic flux through the wire loop. According to Faraday\'s law, this change induces an electromotive force (emf). Since the loop is closed, an induced current flows. By Lenz\'s law, this current flows in a direction such that its magnetic field opposes the original flux change.',
            explanation: 'Induced currents oppose the changes that created them to preserve magnetic equilibrium.'
          }
        ]
      },
      {
        name: 'Thermodynamics & Heat Transfer',
        questions: [
          {
            type: 'MCQ',
            question: 'In an isobaric process, which of the following properties remains constant?',
            options: ['Volume', 'Temperature', 'Pressure', 'Entropy'],
            correctAnswer: '2',
            explanation: 'An isobaric process is a thermodynamic process in which the pressure remains constant (P = constant).'
          },
          {
            type: 'TRUE_FALSE',
            question: 'The entropy of an isolated system can decrease during an irreversible process.',
            correctAnswer: 'false',
            explanation: 'According to the Second Law of Thermodynamics, the entropy of an isolated system always increases in an irreversible process.'
          },
          {
            type: 'ASSERTION_REASON',
            question: 'Assertion: Heat cannot flow on its own from a colder body to a hotter body.\nReason: This violates the conservation of energy.',
            options: [
              'Both Assertion and Reason are true, and Reason is the correct explanation of Assertion.',
              'Both Assertion and Reason are true, but Reason is NOT the correct explanation.',
              'Assertion is true, but Reason is false.',
              'Assertion is false, but Reason is true.'
            ],
            correctAnswer: '2',
            explanation: 'Heat flowing from cold to hot doesn\'t violate the First Law (conservation of energy), but it does violate the Second Law (Clausius statement). Therefore, the reason is false.'
          }
        ]
      }
    ]
  },
  {
    subject: 'Chemistry',
    concepts: [
      {
        name: 'Chemical Kinetics & Reaction Rates',
        questions: [
          {
            type: 'MCQ',
            question: 'If the rate of a reaction doubles when the concentration of a reactant is quadrupled, what is the order of reaction with respect to that reactant?',
            options: ['First order', 'Half order', 'Second order', 'Zero order'],
            correctAnswer: '1',
            explanation: 'Rate is proportional to [A]^n. If concentration increases 4x and rate increases 2x (sqrt of 4), the order is n = 0.5 (half order).'
          },
          {
            type: 'TRUE_FALSE',
            question: 'A catalyst increases the rate of reaction by lowering the activation energy.',
            correctAnswer: 'true',
            explanation: 'Catalysts provide an alternative pathway with a lower activation energy barrier, allowing more molecules to react at a given temperature.'
          },
          {
            type: 'MCQ',
            question: 'Which of the following factors does NOT affect the rate of a chemical reaction?',
            options: ['Concentration of reactants', 'Temperature', 'Enthalpy of reaction', 'Presence of catalyst'],
            correctAnswer: '2',
            explanation: 'Enthalpy (dH) is a thermodynamic property indicating overall heat released or absorbed, which does not affect the speed/rate of the reaction.'
          }
        ]
      },
      {
        name: 'Organic Compounds & Hybridization',
        questions: [
          {
            type: 'MCQ',
            question: 'What is the hybridization of carbon atoms in benzene (C6H6)?',
            options: ['sp3', 'sp2', 'sp', 'dsp2'],
            correctAnswer: '1',
            explanation: 'Each carbon atom in benzene is bonded to three other atoms (two carbons and one hydrogen) via three sigma bonds, resulting in sp2 hybridization.'
          },
          {
            type: 'TRUE_FALSE',
            question: 'Alkanes are generally more reactive than alkenes because they contain single bonds.',
            correctAnswer: 'false',
            explanation: 'Alkenes contain carbon-carbon double bonds (pi bonds), which are electron-rich and much more reactive to electrophilic additions than alkane single bonds.'
          }
        ]
      }
    ]
  },
  {
    subject: 'Mathematics',
    concepts: [
      {
        name: 'Limits, Continuity & Derivatives',
        questions: [
          {
            type: 'MCQ',
            question: 'What is the derivative of f(x) = ln(sin(x)) with respect to x?',
            options: ['tan(x)', 'cot(x)', 'sec(x)', 'csc(x)'],
            correctAnswer: '1',
            explanation: 'By the chain rule, d/dx[ln(sin(x))] = (1/sin(x)) * cos(x) = cot(x).'
          },
          {
            type: 'TRUE_FALSE',
            question: 'If a function f(x) is continuous at x = a, it must be differentiable at x = a.',
            correctAnswer: 'false',
            explanation: 'Continuity is a necessary but not sufficient condition for differentiability. For example, f(x) = |x| is continuous at x = 0 but not differentiable there.'
          },
          {
            type: 'MCQ',
            question: 'Evaluate the limit of (sin(x)/x) as x approaches 0.',
            options: ['0', '1', 'Infinity', 'Undefined'],
            correctAnswer: '1',
            explanation: 'According to the standard trigonometric limit theorem, lim (x -> 0) sin(x)/x = 1.'
          }
        ]
      },
      {
        name: 'Probability & Distributions',
        questions: [
          {
            type: 'MCQ',
            question: 'A fair coin is flipped 3 times. What is the probability of getting exactly 2 heads?',
            options: ['3/8', '1/2', '1/4', '3/4'],
            correctAnswer: '0',
            explanation: 'The sample space has 8 outcomes. The successful outcomes are HHT, HTH, THH (3 outcomes). Probability = 3/8.'
          },
          {
            type: 'TRUE_FALSE',
            question: 'For a normal distribution, approximately 95% of the data lies within one standard deviation of the mean.',
            correctAnswer: 'false',
            explanation: 'Approximately 68% of data lies within one standard deviation. 95% lies within two standard deviations.'
          }
        ]
      }
    ]
  }
];

export const AIAgent = {
  // Extract key concepts from file name / description
  extractConcepts(fileName: string, fileContentText: string): string[] {
    const combined = (fileName + ' ' + fileContentText).toLowerCase();
    const keywords: string[] = [];

    if (combined.includes('electromagnet') || combined.includes('induction') || combined.includes('physics') || combined.includes('flux')) {
      keywords.push('Electromagnetism & Induction');
    }
    if (combined.includes('thermo') || combined.includes('heat') || combined.includes('entropy')) {
      keywords.push('Thermodynamics & Heat Transfer');
    }
    if (combined.includes('kinetic') || combined.includes('rate') || combined.includes('catalyst')) {
      keywords.push('Chemical Kinetics & Reaction Rates');
    }
    if (combined.includes('organic') || combined.includes('carbon') || combined.includes('benzene')) {
      keywords.push('Organic Compounds & Hybridization');
    }
    if (combined.includes('limit') || combined.includes('derivative') || combined.includes('calculus')) {
      keywords.push('Limits, Continuity & Derivatives');
    }
    if (combined.includes('probab') || combined.includes('coin') || combined.includes('distribution')) {
      keywords.push('Probability & Distributions');
    }

    // Default return if nothing matched
    if (keywords.length === 0) {
      keywords.push('General Foundations');
    }
    return keywords;
  },

  // Generate personalized adaptive quiz
  generateQuiz(
    title: string,
    subject: string,
    batch: string,
    sourceFileName: string,
    difficulty: 'EASY' | 'MEDIUM' | 'HARD' | 'ADAPTIVE',
    targetStudentId?: string // Optional: target student to personalize questions
  ): Omit<Quiz, 'id' | 'createdAt'> {
    
    // Find concept pools matching this subject
    const subjectPools = AI_QUESTION_POOL.find(p => p.subject.toLowerCase() === subject.toLowerCase());
    
    let activeConcepts = subjectPools 
      ? subjectPools.concepts 
      : AI_QUESTION_POOL[0].concepts; // fallback

    // If we have a file name, extract matching concepts
    const extractedNames = this.extractConcepts(sourceFileName, title);
    if (extractedNames.length > 0 && extractedNames[0] !== 'General Foundations') {
      const filtered = activeConcepts.filter(c => extractedNames.includes(c.name));
      if (filtered.length > 0) {
        activeConcepts = filtered;
      }
    }

    // Accumulate questions from active concepts
    let questionBank: Omit<Question, 'id'>[] = [];
    activeConcepts.forEach(c => {
      questionBank.push(...c.questions);
    });

    // Fallback if no questions
    if (questionBank.length === 0) {
      questionBank = AI_QUESTION_POOL[0].concepts[0].questions;
    }

    // Apply adaptive difficulty modifications if targetStudentId is provided
    let finalDifficulty: 'EASY' | 'MEDIUM' | 'HARD' = 'MEDIUM';
    
    if (difficulty === 'ADAPTIVE' && targetStudentId) {
      const student = db.getStudentById(targetStudentId);
      if (student) {
        // High performing students get harder questions
        if (student.accuracyPct >= 85 || student.rank <= 2) {
          finalDifficulty = 'HARD';
        } 
        // Lower performing students get easier revision questions
        else if (student.accuracyPct < 70) {
          finalDifficulty = 'EASY';
        }
      }
    } else if (difficulty !== 'ADAPTIVE') {
      finalDifficulty = difficulty;
    }

    // Filter questions by type / difficulty (simulation)
    // EASY: More True/False, less assertions/case studies
    // HARD: More MCQs with complex explanations, Assertion Reason, Case studies
    let selectedQuestions = [...questionBank];
    
    if (finalDifficulty === 'EASY') {
      // Prioritize True/False and MCQ
      selectedQuestions.sort((a, b) => {
        if (a.type === 'TRUE_FALSE') return -1;
        if (b.type === 'TRUE_FALSE') return 1;
        return 0;
      });
    } else if (finalDifficulty === 'HARD') {
      // Prioritize Case study and Assertion Reason
      selectedQuestions.sort((a, b) => {
        if (a.type === 'CASE_STUDY' || a.type === 'ASSERTION_REASON') return -1;
        if (b.type === 'CASE_STUDY' || b.type === 'ASSERTION_REASON') return 1;
        return 0;
      });
    }

    // Slice to 3 questions for a short immersive mock quiz experience
    const finalQuestions: Question[] = selectedQuestions.slice(0, 3).map((q, idx) => ({
      ...q,
      id: `ai-q-${idx}-${Date.now()}`
    }));

    return {
      title: `${title} [AI ${finalDifficulty}]`,
      description: `Automatically compiled by Tuition AI Agent from document "${sourceFileName}". Tailored to student performance requirements.`,
      type: finalQuestions[0]?.type || 'MCQ',
      batch,
      subject,
      durationMin: finalQuestions.length * 5,
      questions: finalQuestions,
      difficulty: finalDifficulty,
      isAiGenerated: true,
      sourceFile: sourceFileName
    };
  }
};
